### ISSUE TITLE
使用cocodpods 集成EaseUI 好多错误， 我特地新建一个项目集成

### ISSUE THREAD

**Issue by fenggeren** [easemob/easeui_ios#11]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_EMChatImage", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMChatImageOptions", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMChatLocation", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMChatText", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMChatVideo", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMChatVoice", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMImageMessageBody", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMLocationMessageBody", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMMessage", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMTextMessageBody", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMVideoMessageBody", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EMVoiceMessageBody", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
  "_OBJC_CLASS_$_EaseMob", referenced from:
      objc-class-ref in libEaseUI.a(EaseSDKHelper.o)
      objc-class-ref in libEaseUI.a(EaseConversationListViewController.o)
      objc-class-ref in libEaseUI.a(EaseUsersListViewController.o)
      objc-class-ref in libEaseUI.a(EaseMessageViewController.o)
      objc-class-ref in libEaseUI.a(EaseMessageModel.o)
      objc-class-ref in libEaseUI.a(NSObject+EaseMob.o)
  "___gxx_personality_v0", referenced from:
      +[EMVoiceConverter isMP3File:] in libEaseUI.a(EMVoiceConverter.o)
      +[EMVoiceConverter isAMRFile:] in libEaseUI.a(EMVoiceConverter.o)
      +[EMVoiceConverter amrToWav:wavSavePath:] in libEaseUI.a(EMVoiceConverter.o)
      +[EMVoiceConverter wavToAmr:amrSavePath:] in libEaseUI.a(EMVoiceConverter.o)
      Dwarf Exception Unwind Info (__eh_frame) in libEaseUI.a(EMVoiceConverter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by xilin** [comment]
pod上的EaseUI看起来是很久都没更新过了
直接上源码吧

**Comment by 110440** [comment]
真心写的不怎样，，看视频上的教程一大坨警告就算集成完了。。我去

**Comment by DearX-dlx** [comment]
项目集成在那里
