### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by ferrior30** [easemob/easeui_ios#5]
![snip20151210_2](https://cloud.githubusercontent.com/assets/12984460/11710234/9c1ae73c-9f58-11e5-961b-c0e24f3821bf.png)

**Comment by shengdoushi** [comment]
自己调整下include目录吧， 这个库说实话， 集成上简直很糟。

1. 自己内部集成了很多第三方库。和我本地的冲突， 版本不一致的干活
2. 自己内部集成了 easemob 基础库， 我早先项目已经有了
3. 自己内部会更改全局的ui风格， 我只想作为一部分放到我项目中好不好

所以我自己克隆下来自己修改里边的东西了只好。
