### ISSUE TITLE
导入easeUI后找不到头文件

### ISSUE THREAD

**Issue by sichangfeng** [easemob/easeui_ios#69]
你好，我想问下，我通过cocoa pods导入ease UI后运行项目提示找不到Hyphenate.h文件，是什么原因？Hyphenate我已经通过cocoa pods导入了

**Comment by lizilong1989** [comment]
@sichangfeng 是不是podfile中用到"use_frameworks!" ?

**Comment by sichangfeng** [comment]
podfile中没有用到，还有其他可能的原因吗

**Comment by lizilong1989** [comment]
@sichangfeng 我这边测试是没有任何问题的, 你也集成的是Hyphenate?
pod 'Hyphenate'
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git'

**Comment by sichangfeng** [comment]
是，我pod写的和你一模一样，还尝试了HyphenateLite也不行

**Comment by lizilong1989** [comment]
@sichangfeng 你是怎么引用头文件的?

**Comment by sichangfeng** [comment]
我直接在import Hyphenate是没有问题的，报错的是在EaseUI中本身有一个文件#import <Hyphenate/Hyphenate.h>，运行项目提示找不到这个文件。但是在项目其他地方导入好像没有报这个错。

**Comment by lizilong1989** [comment]
@sichangfeng 你检查一下podfile是不是用了use_frameworks!
