### ISSUE TITLE
TableView被遮挡

### ISSUE THREAD

**Issue by sichangfeng** [easemob/easeui_ios#70]
你好，我想问下，我通过push的方式转场到聊天界面，tableView被顶部的navigationBar挡住了，应该怎么设置？

**Comment by lizilong1989** [comment]
@sichangfeng 你可用xcode "Debug view hierarchy", 看一下页面结构

**Comment by lizilong1989** [comment]
@sichangfeng 判断是挡住了, 还是没有显示

**Comment by sichangfeng** [comment]
OK，搞定了，谢谢，tableView的frame问题
