### ISSUE TITLE
聊天汽泡宽度能否设置为  屏幕宽度-120  ?

### ISSUE THREAD

**Issue by sunbohong** [easemob/easeui_ios#8]

**Comment by lizilong1989** [comment]
可以,在viewdidload中设置[[EaseMessageCell appearance] setBubbleMaxWidth:120],这个是气泡最大宽度

**Comment by sunbohong** [comment]
@lizilong1989  我的意思是   屏幕宽度 -120 。6p上面显示的汽泡宽度太小了。

**Comment by lizilong1989** [comment]
@sunbohong 这个可以宽度自己设置,根据app的需求
