### ISSUE TITLE
下载后直接运行不了

### ISSUE THREAD

**Issue by 1170197998** [easemob/easeui_ios#87]
这个是环信官方的demo吗，下载后就直接运行不了，资源没有上传完整，直接报错。。。。。。。上传上去了测试下哈

**Comment by lizilong1989** [comment]
@1170197998 Hi，您好，这个不是完整的demo，完整的demo地址:https://github.com/easemob/sdkdemoapp3.0_ios/tree/sdk3.x

**Comment by 1170197998** [comment]
谢谢
