### ISSUE TITLE
现在不支持cocoaPods了吗?

### ISSUE THREAD

**Issue by darkThanBlack** [easemob/easeui_ios#9]

**Comment by lizilong1989** [comment]
支持
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'

**Comment by lizilong1989** [comment]
@darkThanBlack 支持
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'

**Comment by darkThanBlack** [comment]
好的谢谢;不过希望能将项目中的三方类替换为cocoaPods形式,手动更新处理冲突颇为麻烦

**Comment by lizilong1989** [comment]
@darkThanBlack 
easeui第三方依赖也是cocoaPods形式,现在还报那些依赖冲突的错误?
`
spec.dependency 'MWPhotoBrowser', '~> 2.1.1'
spec.dependency 'MJRefresh', '~> 3.0.6'
`

**Comment by darkThanBlack** [comment]
改了是吧,那就好,我是自己从官网下载DEMO处理的,好像你们的自动聊天机器人列表只有用DEMO的KEY的时候才能取到,这个是我集成写法的问题还是什么?要不要考虑在文档里面说明一下?

**Comment by lizilong1989** [comment]
@darkThanBlack 聊天机器人需要配置appkey才能取到,暂时只是一个演示聊天功能

**Comment by zzgo** [comment]
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:
- `MJRefresh (~> 3.0.6)` required by `EaseUI (1.0.0)`

报这个错

**Comment by darkThanBlack** [comment]
我是自己从官网下载DEMO后手动去修改的,把相关第三方记录下来删掉,再去cocoaPods更新,再把过时的方法给替换掉.

**Comment by zzgo** [comment]
好的，谢谢啦！
