### ISSUE TITLE
发送图片或视频消息的进度怎么监听

### ISSUE THREAD

**Issue by jinghailang** [easemob/easeui_ios#94]
- (void)sendImageMessageWithData:(NSData *)imageData
{
    id progress = nil;
    if (_dataSource && [_dataSource respondsToSelector:@selector(messageViewController:progressDelegateForMessageBodyType:)]) {
        progress = [_dataSource messageViewController:self progressDelegateForMessageBodyType:EMMessageBodyTypeImage];
    }
    else{
        progress = self;
    }
    
    EMMessage *message = [EaseSDKHelper sendImageMessageWithImageData:imageData
                                                                   to:self.conversation.conversationId
                                                          messageType:[self _messageTypeFromConversationType]
                                                           messageExt:nil];
    [self _sendMessage:message];
}

这个方法里面的progress有什么用？？？

**Comment by xieyajie** [comment]
你好，因为EaseUI项目历时时间比较久，很长时间没有维护了。就代码里来看，progress没有任何地方用到。
